name: Unity CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest

  # Cache Lib Folders
    steps:
    - uses: actions/cache@v1.1.0
      with:
        path: ./Library
        key: Library-MyProjectName-TargetPlatform
        restore-keys: |
          Library-unit-ci-
          Library-
    # Run tests
    - uses: webbertakken/unity-test-runner@v1.4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ./
        unityVersion: 2019.4.2f1

    # Upload Test results
    - uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: artifacts
