name: BUILD / Node.js Server for WebGL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_server:
    runs-on: ubuntu-latest
    needs: [build_unity]
    steps:
      - run: bash scripts/setup-server.sh
